# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/thenujan/Desktop/Code/system_maintenance_pyqt/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 153)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_rm_journal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rm_journal.setObjectName("btn_rm_journal")
        self.gridLayout.addWidget(self.btn_rm_journal, 1, 0, 1, 1)
        self.btn_mirrors = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mirrors.setObjectName("btn_mirrors")
        self.gridLayout.addWidget(self.btn_mirrors, 0, 0, 1, 1)
        self.btn_swap = QtWidgets.QPushButton(self.centralwidget)
        self.btn_swap.setObjectName("btn_swap")
        self.gridLayout.addWidget(self.btn_swap, 0, 1, 1, 1)
        self.btn_rm_cache = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rm_cache.setObjectName("btn_rm_cache")
        self.gridLayout.addWidget(self.btn_rm_cache, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "System Maintenance"))
        self.btn_rm_journal.setText(_translate("MainWindow", "remove journalctl logs"))
        self.btn_mirrors.setText(_translate("MainWindow", "mirrors"))
        self.btn_swap.setText(_translate("MainWindow", "swap memory"))
        self.btn_rm_cache.setText(_translate("MainWindow", "remove cache in home directory"))
