# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/thenujan/Desktop/Code/system_maintenance_pyqt/swap_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(106, 82)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_file = QtWidgets.QPushButton(Form)
        self.btn_file.setObjectName("btn_file")
        self.verticalLayout.addWidget(self.btn_file)
        self.btn_partition = QtWidgets.QPushButton(Form)
        self.btn_partition.setObjectName("btn_partition")
        self.verticalLayout.addWidget(self.btn_partition)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_file.setText(_translate("Form", "swap file"))
        self.btn_partition.setText(_translate("Form", "swap partition"))
